#poc for lambda canary deployments
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GHToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: token

Resources:
  
  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: GHToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetAction: Source
      TargetPipeline: !Ref Pipeline
      TargetPipelineVersion: 1
      RegisterWithThirdParty: true

  CodePipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
                - codebuild.amazonaws.com
                - ecs.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
          PolicyName: AllPermissions
      RoleName: CanaryCodePipelineRole

  CanaryBuild:
    Type: AWS::CodeBuild::Project
    Properties: 
      Artifacts: 
        Type: CODEPIPELINE
      Description: Canary Build Project
      Environment: 
        EnvironmentVariables:
          - Name: template_file
            Type: PLAINTEXT
            Value: canaryservice.yml
          - Name: package_bucket
            Type: PLAINTEXT
            Value: !Ref ArtifactBucket
          - Name: package_file
            Type: PLAINTEXT
            Value: canaryservice-package.yml
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      LogsConfig: 
        CloudWatchLogs:
          Status: DISABLED
      Name: CanaryBuild
      QueuedTimeoutInMinutes: 20
      ServiceRole: !GetAtt CodePipelineExecutionRole.Arn
      Source: 
        BuildSpec: code/buildspec.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineExecutionRole.Arn
      Stages:
        - Actions:
          - ActionTypeId:
              Category: Source
              Owner: ThirdParty
              Provider: GitHub
              Version: '1'
            Configuration:
              Owner: ZhangMaKe
              Repo: CanaryLambda
              Branch: master
              OAuthToken: !Ref GHToken
              PollForSourceChanges: false
            Name: Source 
            OutputArtifacts:
              - Name: source
          Name: Source
        - Actions:
          - ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              OutputFileName: pipelineStackOutput.json
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !GetAtt CodePipelineExecutionRole.Arn
              StackName: Canary
              ActionMode: CREATE_UPDATE
              TemplatePath: source::poc.yml
            InputArtifacts:
              - Name: source
            RoleArn: !GetAtt CodePipelineExecutionRole.Arn
            RunOrder: 1
            Name: Stack
          Name: AdministerPipeline
        - Actions:
          - ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            Configuration:
              ProjectName: CanaryBuild
            InputArtifacts:
              - Name: source
            Name: BuildCanaryFunction
            OutputArtifacts:
              - Name: code
            RoleArn: !GetAtt CodePipelineExecutionRole.Arn
            RunOrder: 1
          - ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              OutputFileName: canaryServiceStackOutput.json
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !GetAtt CodePipelineExecutionRole.Arn
              StackName: CanaryService
              ActionMode: CREATE_UPDATE
              TemplatePath: code::canaryservice-package.yml
            InputArtifacts:
              - Name: code
            RoleArn: !GetAtt CodePipelineExecutionRole.Arn
            RunOrder: 2
            Name: CanaryServiceStack
          Name: CanaryService
      ArtifactStores:
        - ArtifactStore:
            Location: !Ref ArtifactBucket
            Type: S3
          Region: us-east-1
      Name: CanaryPipeline

  ArtifactBucket:
    Type: AWS::S3::Bucket