#poc for lambda canary deployments
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GHToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: token

Resources:
  
  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: GHToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetAction: Source
      TargetPipeline: !Ref Pipeline
      TargetPipelineVersion: 1
      RegisterWithThirdParty: true

  CodePipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
          PolicyName: AllPermissions
      RoleName: CanaryCodePipelineRole

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineExecutionRole.Arn
      Stages:
        - Actions:
          - ActionTypeId:
              Category: Source
              Owner: ThirdParty
              Provider: GitHub
              Version: '1'
            Configuration:
              Owner: ZhangMaKe
              Repo: CanaryLambda
              Branch: master
              OAuthToken: !Ref GHToken
              PollForSourceChanges: false
            Name: Source 
            OutputArtifacts:
              - Name: source
          Name: Source
        - Actions:
          - ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              OutputFileName: pipelineStackOutput.json
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !GetAtt CodePipelineExecutionRole.Arn
              StackName: Canary
              ActionMode: CREATE_UPDATE
              TemplatePath: source::poc.yml
            InputArtifacts:
              - Name: source
            RoleArn: !GetAtt CodePipelineExecutionRole.Arn
            RunOrder: 1
            Name: Stack
          Name: AdministerPipeline
        - Actions:
          - ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: '1'
            Configuration:
              OutputFileName: canaryServiceStackOutput.json
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !GetAtt CodePipelineExecutionRole.Arn
              StackName: CanaryService
              ActionMode: CREATE_UPDATE
              TemplatePath: source::canaryservice.yml
            InputArtifacts:
              - Name: source
            RoleArn: !GetAtt CodePipelineExecutionRole.Arn
            RunOrder: 1
            Name: CanaryServiceStack
          Name: CanaryService
      ArtifactStores:
        - ArtifactStore:
            Location: !Ref ArtifactBucket
            Type: S3
          Region: us-east-1
      Name: CanaryPipeline

  ArtifactBucket:
    Type: AWS::S3::Bucket