version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  build:
    commands:
      - echo build
      - pip install aws-sam-cli
      - sam package --template-file $template_file --s3-bucket  $package_bucket --debug --output-template-file $package_file
artifacts:
  files:
    - canaryservice-package.yml